@startuml

title MenuActivity Domain Model
class MenuActivity {
tabs
}
class Score{
highScore
currentScore
}

class Game {
buttonSequence
playerSequence
blueButton
redButton
yellowButton
greenButton
}

MenuActivity "1" *- "2" Score: publishes high score >

MenuActivity "1" *-- "2" Game: implements >



hide empty members
hide methods

@enduml