@startuml
title Use Case Diagram

actor Player
actor Simon

rectangle  {

    usecase "Press a Colored Button" as UC_player_1
    Player -- UC_player_1
    UC_player_1 ..> (Correct Button): <<includes>>
    UC_player_1 ..> (Incorrect Button): <<includes>>

    usecase "Remember Sequence of Colors" as UC_simon_1
    Simon -- UC_simon_1
    UC_simon_1 ..> (Incorrect Button Pressed): <<includes>>
    UC_simon_1 ..> (Correct Button Pressed): <<includes>>
    (Correct Button Pressed) <. (High Score) : <<extends>>


}
@enduml

