@startsalt
{
{T
+ Press a Colored Sequence
++  Goal
+++ To press one of the four available colored buttons.
++ Entry conditions
+++ The player has started the game and has not pressed an incorrect button yet.
++ Scenario
+++ The player has to remember what Simon has been "saying"
+++ The player must input the correct sequence of colors that Simon has said
++ Exceptions
+++ The game is continuous and must be terminated
++ Exit conditions
+++ Successful Exit Conditions
++++ The game is terminated/completed.
+++ Failure Exit Conditions
++++ None
}
---
{T
+ Sequence of Colors
++  Goal
+++ To implement a random sequence of colors.
++ Entry conditions
+++ The game must have started and not be terminated
++ Scenario
+++ Another color is added to the end of the sequence after each correct sequence is pressed.
++ Exceptions
+++ The user presses the incorrect button
++ Exit conditions
+++ Successful Exit Conditions
++++ The correct button in the sequence is pressed
+++ Failure Exit Conditions
++++ The incorrect button in the sequence is pressed, terminating the game.
}
---
{T
+ Correct Button
++  Goal
+++ To input the correct color as the next sequence in what Simon said
++ Entry conditions
+++ The game must have started and not be terminated
++ Scenario
+++ The user presses the correct color in the current sequence.
++ Exceptions
+++ The user presses the incorrect button
++ Exit conditions
+++ Successful Exit Conditions
++++ The correct button in the sequence is pressed
+++ Failure Exit Conditions
++++ The incorrect button in the sequence is pressed, terminating the game.
}
---
{T
+ Incorrect Button
++  Goal
+++ To input the incorrect color as the next sequence in what Simon said
++ Entry conditions
+++ The game must have started and not be terminated
++ Scenario
+++ The user presses the incorrect color in the current sequence.
++ Exceptions
+++ The user presses the correct button
++ Exit conditions
+++ Successful Exit Conditions
++++ The incorrect button in the sequence is pressed
+++ Failure Exit Conditions
++++ The correct button in the sequence is pressed, leading to the next color.
}
---
{T
+ Correct Sequence Pressed
++  Goal
+++ To determine if the player pressed the correct colors.
++ Entry conditions
+++ The game must have started and not be terminated.
++ Scenario
+++ The player presses a certain set of colors hoping it is the correct sequence.
+++ This use case determines if the sequence is correct.
++ Exceptions
+++ None
++ Exit conditions
+++ Successful Exit Conditions
++++ The player presses the correct button.
++++ Another color is added to the sequence.
+++ Failure Exit Conditions
++++ The player presses the incorrect sequence.
}
---
{T
+ Inorrect Sequence Pressed
++  Goal
+++ To determine if the player pressed the incorrect sequence.
++ Entry conditions
+++ The game must have started and not be terminated.
++ Scenario
+++ The player presses a certain set of colors hoping it is the correct sequence.
+++ This use case determines if the sequence is incorrect.
++ Exceptions
+++ None
++ Exit conditions
+++ Successful Exit Conditions
++++ The player presses the incorrect sequence.
++++ The game is terminated and the score is recorded.
+++ Failure Exit Conditions
++++ The player presses the correct button.
}
---
{T
+ Move On
++  Goal
+++ To add to the score and add another color to the sequence.
++ Entry conditions
+++ The game must not be terminated.
++ Scenario
+++ The player enters the correct sequence.
+++ The score is incremented by one
+++ A new color is added to the sequence
++ Exceptions
+++ None
++ Exit conditions
+++ Successful Exit Conditions
++++ The new score is added and a new color is added.
+++ Failure Exit Conditions
++++ None
}
---
{T
+ Game Over
++  Goal
+++ To terminate the game.
++ Entry conditions
+++ The game must be in progress.
++ Scenario
+++ The player enters an incorrect sequence.
+++ The score is recorded
++ Exceptions
+++ None
++ Exit conditions
+++ Successful Exit Conditions
++++ The new score is added along with the high score if it's greater.
+++ Failure Exit Conditions
++++ None
}
---
{T
+ Publish Score
++  Goal
+++ To determine if the player has a score greater than the high score.
++ Entry conditions
+++ The game must be terminated with the player having a score.
++ Scenario
+++ The player ends the game by pressing the incorrect color in the sequence.
+++ This use case determines if the total score is highest
++++ If so, the new score is recorded as the new high score
++++ Otherwise, the score is added to last score
++ Exceptions
+++ None
++ Exit conditions
+++ Successful Exit Conditions
++++ The new high score is recorded, if it is greater than the previous.
+++ Failure Exit Conditions
++++ The new score is not greater than the high score, and is forgotten.
}

}
@endsalt